FROM python:3.10.6-slim

ENV ENV_NAME=production
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

EXPOSE 8000

WORKDIR /app
COPY requirements.txt /app/
RUN pip install -r requirements.txt
COPY . /app/

RUN mkdir /gunicorn-temp

CMD ["gunicorn", "--worker-tmp-dir", "/gunicorn-temp/", "weighbot.wsgi"]