# Generated by Django 4.1 on 2022-08-19 07:43

from django.db import migrations, models
import django.db.models.deletion
import tracking.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4)),
                ('starting', models.DateField()),
                ('started_at', models.DateTimeField(null=True)),
                ('thread_id', models.CharField(max_length=64, null=True)),
                ('finished', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('starting', models.DateField()),
                ('check_in_period', models.PositiveSmallIntegerField(default=7)),
                ('final_check_in', models.DateField()),
                ('channel_id', models.CharField(max_length=64, null=True)),
                ('finished', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discord_id', models.CharField(max_length=64)),
                ('external_id', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=128)),
                ('contest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contestants', to='tracking.contest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContestantCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discord_id', models.CharField(max_length=64)),
                ('external_id', models.UUIDField(default=uuid.uuid4)),
                ('weight', models.FloatField()),
                ('check_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contestant_check_ins', to='tracking.checkin')),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='tracking.contestant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CheckInPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discord_id', models.CharField(max_length=64)),
                ('external_id', models.UUIDField(default=uuid.uuid4)),
                ('kind', models.CharField(blank=True, max_length=32)),
                ('image', models.ImageField(upload_to=tracking.models.check_in_photo_upload_dest)),
                ('contestant_check_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.contestantcheckin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='checkin',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='tracking.contest'),
        ),
    ]
