# Generated by Django 4.1 on 2022-09-05 22:04

from django.db import migrations, models
import django.db.models.deletion


def fill_in_previous(apps, schema_editor):
    CheckIn = apps.get_model('tracking', 'CheckIn')
    for check_in in CheckIn.objects.all().iterator():
        try:
            check_in.previous = check_in.contest.check_ins.filter(starting__lt=check_in.starting).latest('starting')
            check_in.save()
        except CheckIn.DoesNotExist:
            pass


def unfill_previous(apps, schema_editor):
    CheckIn = apps.get_model('tracking', 'CheckIn')
    for check_in in CheckIn.objects.all().iterator():
        check_in.previous = None
        check_in.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_contestantcheckin_message_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='previous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.checkin'),
        ),
        migrations.RunPython(
            fill_in_previous,
            unfill_previous
        )
    ]
